"""Prepare v1.8 ImageGen edits without rewriting any original sprite assets.

Artwork is generated by built-in ImageGen; this tool only extracts/aligns keys,
splits the generated desk into depth layers, and samples optical-flow segments.
Black and yellow eyes never share a segment: a fully shut eyelid key separates
the two expressions in both directions.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image

import prepare_generated_sheets as pipeline
import prepare_work_animation as work
from prepare_care_animation import measure_eat_root
from prepare_busy_fire import fire_root
import work_asset_acceleration


def keyframe(assets: Path, path: str) -> Image.Image:
    return Image.open(assets / path).convert("RGBA")


def write_keys(assets: Path) -> dict:
    sources = assets / "AnimationSources"
    neutral = keyframe(assets, "mascot-animated-neutral.png")
    normal = keyframe(assets, "Animations/WorkLoop/frame-0000.png")
    angry = keyframe(assets, "Animations/BusyLoop/frame-0000.png")
    normal_closed = work.align_cells(work.extract_native_cells(sources / "work-blink-closed-v2.png", 1, 1), normal)[0]
    angry_closed = work.align_cells(work.extract_native_cells(sources / "busy-blink-closed-v2.png", 1, 1), angry)[0]
    # Separate closed-eye keys are a visible anticipation beat, not a dissolve
    # between incompatible eyeballs. Exact existing anchors preserve loop seams.
    clips = {
        "WorkToBusyV2": (1.5, [normal, normal_closed, angry_closed, angry], (0, 18, 42, 90)),
        "BusyExitV2": (2.0, [angry, angry_closed, normal_closed,
                            keyframe(assets, "AnimationKeys/WorkExit/key-01.png"),
                            keyframe(assets, "AnimationKeys/WorkExit/key-02.png"), neutral],
                       (0, 15, 33, 66, 92, 120)),
    }
    result = {}
    for name, (duration, frames, positions) in clips.items():
        directory = assets / "AnimationKeys" / name
        directory.mkdir(parents=True, exist_ok=True)
        for index, frame in enumerate(frames):
            frame.save(directory / f"key-{index:02d}.png", optimize=True)
        spec = pipeline.ClipSpec(name=name, sheet_name="work-scene-v2-blink",
            duration_seconds=duration, columns=len(frames), rows=1, source_pose_count=len(frames),
            authored_frame_indices=positions, segmentwise_interpolation=True)
        pipeline.make_key_contact_sheet(directory, len(frames), assets / "AnimationPreviews" / f"{name}-keys-dark.png")
        result[name] = (spec, frames, directory)

    write_desk(assets)
    return result


def write_desk(assets: Path) -> None:
    sources = assets / "AnimationSources"
    # The panel's opaque lower edge covers the original 336 px foot anchor;
    # its two supports reach 345 px, still wholly within the authored canvas.
    desk = work.place_prop(pipeline.extract_cells(sources / "work-desk-v2.png", 1, 1, 1)[0], 306, 39, 345)
    props = assets / "SceneProps/WorkV2"
    props.mkdir(parents=True, exist_ok=True)
    desk.save(props / "desk.png", optimize=True)
    back, front = np.array(desk), np.array(desk)
    back[276:, :, 3] = 0
    front[:276, :, 3] = 0
    Image.fromarray(back).save(props / "desk-back.png", optimize=True)
    Image.fromarray(front).save(props / "desk-front.png", optimize=True)
    (props / "layout.json").write_text(json.dumps({
        "canvas": [384, 346], "desk_bounds": desk.getbbox(), "split_y": 276,
        "desk_baseline": 345, "avatar_foot_anchor_unchanged": [191.5, 336],
        "occlusion": "Generated closed-front modesty panel naturally occludes seated lower body and feet.",
        "laptop": "../Work/laptop.png", "fire": "Fire/frame-NNNN.png",
    }, indent=2), encoding="utf-8")


def write_fire_keys(assets: Path) -> tuple:
    source = assets / "AnimationSources/busy-fire-sheet-v2.png"
    image = Image.open(source).convert("RGBA")
    rgba = np.array(image)
    # Known red/yellow asset palette removes only the generated outside checker.
    # Unlike v1, the new ImageGen source itself has a solid authored core.
    red, green, blue = [rgba[:, :, c].astype(np.int16) for c in range(3)]
    alpha = np.where((red >= 160) & (red - blue >= 95) & (red - green >= 12), 255, 0).astype(np.uint8)
    rgba[:, :, 3] = np.minimum(rgba[:, :, 3], alpha)
    components = sorted(pipeline.label_alpha_components(rgba[:, :, 3]), key=lambda c: c.area, reverse=True)[:4]
    components.sort(key=lambda c: c.center_y)
    ordered = sorted(components[:2], key=lambda c: c.center_x) + sorted(components[2:], key=lambda c: c.center_x)
    if len(ordered) != 4:
        raise RuntimeError("Expected four generated filled flame poses")
    frames = []
    for item in ordered:
        ys, xs = np.divmod(item.flat_indices, image.width)
        crop = np.zeros((item.maximum_y - item.minimum_y + 1, item.maximum_x - item.minimum_x + 1, 4), dtype=np.uint8)
        crop[ys - item.minimum_y, xs - item.minimum_x] = rgba[ys, xs]
        art = pipeline.add_rgb_edge_bleed(Image.fromarray(crop), iterations=12).resize((258, 282), Image.Resampling.LANCZOS)
        frame = Image.new("RGBA", pipeline.CANVAS_SIZE)
        frame.alpha_composite(art, (63, 53))
        frames.append(pipeline.add_rgb_edge_bleed(pipeline.selective_matte_defringe(frame)))
    frames.append(frames[0].copy())
    pipeline.measure_root_anchor = fire_root
    frames, _ = pipeline.stabilize_frames(frames, frames[0], exact_endpoints=(frames[0], frames[0]))
    directory = assets / "AnimationKeys/BusyFireV2"
    directory.mkdir(parents=True, exist_ok=True)
    for index, frame in enumerate(frames):
        frame.save(directory / f"key-{index:02d}.png", optimize=True)
    spec = pipeline.ClipSpec(name="BusyFireV2", sheet_name=source.name, duration_seconds=2,
        columns=5, rows=1, source_pose_count=5, authored_frame_indices=(0, 30, 60, 90, 120),
        segmentwise_interpolation=True)
    pipeline.make_key_contact_sheet(directory, len(frames), assets / "AnimationPreviews/BusyFireV2-keys-dark.png")
    return spec, frames, directory


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assets", type=Path, required=True)
    parser.add_argument("--rife", type=Path)
    parser.add_argument("--rife-model", type=Path)
    parser.add_argument("--phase", choices=("keys", "props", "fire", "WorkToBusyV2", "BusyExitV2"), default="keys")
    args = parser.parse_args()
    assets = args.assets.resolve(strict=True)
    work_asset_acceleration.enable(pipeline)
    if args.phase == "props":
        write_desk(assets)
        return
    if args.phase == "keys":
        write_keys(assets)
        write_fire_keys(assets)
        return
    if args.rife is None or args.rife_model is None:
        raise SystemExit("Interpolation requires --rife and --rife-model")
    if args.phase == "fire":
        spec, frames, directory = write_fire_keys(assets)
        pipeline.measure_root_anchor = fire_root
        target = assets / "SceneProps/WorkV2/Fire"
        neutral = frames[0]
    else:
        duration, positions = {"WorkToBusyV2": (1.5, (0, 18, 42, 90)),
                               "BusyExitV2": (2.0, (0, 15, 33, 66, 92, 120))}[args.phase]
        directory = assets / "AnimationKeys" / args.phase
        frames = [Image.open(directory / f"key-{i:02d}.png").convert("RGBA") for i in range(len(positions))]
        spec = pipeline.ClipSpec(name=args.phase, sheet_name="work-scene-v2-blink",
            duration_seconds=duration, columns=len(frames), rows=1, source_pose_count=len(frames),
            authored_frame_indices=positions, segmentwise_interpolation=True)
        pipeline.measure_root_anchor = measure_eat_root
        target = assets / "Animations" / args.phase
        neutral = keyframe(assets, "mascot-animated-neutral.png")
    print(f"Exact versioned output: {target}", flush=True)
    count, qa = pipeline.run_rife(args.rife.resolve(strict=True), args.rife_model.resolve(strict=True),
        directory, target, spec, neutral, exact_endpoints=(frames[0], frames[-1]))
    final, _, _ = pipeline.load_frame_sequence(target)
    hashes = [hashlib.sha256(frame.tobytes()).hexdigest() for frame in final]
    qa["unique_pixel_frames"] = len(set(hashes))
    qa["provenance"] = {"generator": "built-in imagegen", "version": "work-scene-v2",
        "closed_eye_barrier": args.phase != "fire", "source_edits_preserved": True}
    pipeline.write_qa_report(assets / "AnimationPreviews" / f"{spec.name}-qa.json", qa)
    pipeline.make_dark_background_contact_sheet(target, count, assets / "AnimationPreviews" / f"{spec.name}-dark.png")
    pipeline.make_60fps_gif(target, count, assets / "AnimationPreviews" / f"{spec.name}-60fps.gif")
    print(f"{spec.name}: {count} frames, {len(set(hashes))} unique, QA {qa['passed']}", flush=True)


if __name__ == "__main__":
    main()
